import docx
from docx.shared import Inches, Pt, RGBColor
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from tools.database_tools import get_size_category


def set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    """Set padding/margins for a table cell in twentieths of a point (dxa)."""
    tcPr = cell._tc.get_or_add_tcPr()
    tcMar = OxmlElement('w:tcMar')
    for m, val in [('w:top', top), ('w:bottom', bottom), ('w:left', left), ('w:right', right)]:
        node = OxmlElement(m)
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tcMar.append(node)
    tcPr.append(tcMar)


def create_table_summary_document(overall_summary, table_summaries, output_path):
    """
    Compiles the Table Summary Report into a Microsoft Word document (.docx)
    using the structured summaries generated by the AI Table Summarizer agent.
    """
    print(f"[INFO] Compiling Table Summary Report to DOCX: {output_path}...")
    doc = docx.Document()
    
    title_p = doc.add_paragraph()
    run = title_p.add_run("TABLE SUMMARY REPORT")
    run.font.name = 'Outfit'
    run.font.size = Pt(24)
    run.font.bold = True
    run.font.color.rgb = RGBColor(15, 76, 129)
    title_p.paragraph_format.space_after = Pt(20)
    
    h_overall = doc.add_paragraph()
    r = h_overall.add_run("OVERALL METADATA SUMMARY")
    r.font.name = 'Outfit'
    r.font.size = Pt(16)
    r.font.bold = True
    r.font.color.rgb = RGBColor(15, 76, 129)
    h_overall.paragraph_format.space_before = Pt(12)
    h_overall.paragraph_format.space_after = Pt(6)
    
    for line in overall_summary.strip().split("\n"):
        if not line:
            continue
        p = doc.add_paragraph()
        p.paragraph_format.space_after = Pt(4)
        if ":" in line:
            parts = line.split(":", 1)
            p.add_run(parts[0] + ":").bold = True
            p.add_run(parts[1])
        else:
            p.add_run(line)
            
    p_sep = doc.add_paragraph()
    p_sep.add_run("--------------------------------------------------").font.color.rgb = RGBColor(128, 128, 128)
    p_sep.paragraph_format.space_after = Pt(12)
    
    for i, summary in enumerate(table_summaries):
        lines = summary.split("\n")
        
        for line in lines:
            if not line.strip():
                continue
            
            p = doc.add_paragraph()
            p.paragraph_format.space_after = Pt(3)
            
            if line.startswith("Table Name:"):
                p.paragraph_format.space_before = Pt(12)
                parts = line.split(":", 1)
                run_label = p.add_run("Table Name: ")
                run_label.bold = True
                run_label.font.size = Pt(13)
                run_label.font.color.rgb = RGBColor(15, 76, 129)
                run_val = p.add_run(parts[1].strip())
                run_val.bold = True
                run_val.font.size = Pt(13)
                run_val.font.color.rgb = RGBColor(15, 76, 129)
            elif line.startswith("Schema:"):
                parts = line.split(":", 1)
                p.add_run("Schema: ").bold = True
                p.add_run(parts[1].strip())
            elif line.startswith("General Info:") or line.startswith("Structure:") or line.startswith("Dependencies:") or line.startswith("Usage:") or line.startswith("Summary:"):
                p.paragraph_format.space_before = Pt(8)
                run_sec = p.add_run(line)
                run_sec.bold = True
                run_sec.font.color.rgb = RGBColor(40, 116, 166)
            elif line.startswith("- "):
                parts = line.split(":", 1)
                p.add_run(parts[0] + ":").bold = True
                if len(parts) > 1:
                    p.add_run(parts[1])
            elif "•" in line:
                p.paragraph_format.left_indent = Inches(0.25)
                p.add_run(line)
            else:
                p.add_run(line)
                
        if i < len(table_summaries) - 1:
            p_sep = doc.add_paragraph()
            p_sep.paragraph_format.space_before = Pt(12)
            p_sep.paragraph_format.space_after = Pt(12)
            p_sep.add_run("--------------------------------------------------").font.color.rgb = RGBColor(128, 128, 128)
            
    doc.save(output_path)
    print(f"[INFO] Successfully saved Table Summary Report.")


def create_migration_plan_document(tables_df, columns_df, stats_df, dep_df, views_df, procedures_df, agent_writeups, output_path, tokens_used=None):
    """
    Compiles the 9-Section Database Migration Assessment Report into a Microsoft Word document (.docx)
    driven by the AI Migration Plan Generator agent writeups and metadata context.
    """
    print(f"[INFO] Compiling Migration Plan Report to DOCX: {output_path}...")
    doc = docx.Document()
    
    title_p = doc.add_paragraph()
    run = title_p.add_run("Database Migration Plan")
    run.font.name = 'Outfit'
    run.font.size = Pt(26)
    run.font.bold = True
    run.font.color.rgb = RGBColor(15, 76, 129)
    
    subtitle_p = doc.add_paragraph()
    run_sub = subtitle_p.add_run("AI Generated Migration Report (Microsoft Azure AI Foundry)")
    run_sub.font.name = 'Outfit'
    run_sub.font.size = Pt(14)
    run_sub.font.italic = True
    run_sub.font.color.rgb = RGBColor(100, 100, 100)
    subtitle_p.paragraph_format.space_after = Pt(24)
    
    # Parse agent writeups into sections
    sections = {}
    current_sec = None
    sec_content = []
    
    for line in agent_writeups.split("\n"):
        line_stripped = line.strip()
        sec_matched = False
        for sec_num in range(1, 10):
            if f"SECTION {sec_num}" in line_stripped.upper():
                if current_sec:
                    sections[current_sec] = "\n".join(sec_content)
                current_sec = sec_num
                sec_content = []
                sec_matched = True
                break
        if not sec_matched and current_sec:
            sec_content.append(line)
            
    if current_sec:
        sections[current_sec] = "\n".join(sec_content)
        
    def render_section_text(sec_num, title, default_desc):
        p_h = doc.add_paragraph()
        r = p_h.add_run(f"SECTION {sec_num}: {title.upper()}")
        r.font.size = Pt(18)
        r.font.bold = True
        r.font.color.rgb = RGBColor(15, 76, 129)
        p_h.paragraph_format.space_before = Pt(18)
        
        raw_text = sections.get(sec_num, "").strip()
        lines = []
        for line in raw_text.split("\n"):
            line_str = line.strip()
            line_str = line_str.replace("###", "").replace("**", "").replace("__", "").replace("|", "")
            if line_str:
                lines.append(line_str)
                
        content_text = "\n".join(lines) if lines else default_desc
        for paragraph in content_text.split("\n"):
            if paragraph.strip():
                p = doc.add_paragraph()
                p.paragraph_format.space_after = Pt(4)
                if paragraph.strip().startswith("- "):
                    p.paragraph_format.left_indent = Inches(0.25)
                    parts = paragraph.strip()[2:].split(":", 1)
                    if len(parts) > 1:
                        p.add_run(parts[0] + ":").bold = True
                        p.add_run(parts[1])
                    else:
                        p.add_run(paragraph.strip()[2:])
                else:
                    p.add_run(paragraph.strip())

    # ------------------ SECTION 1: METADATA INTERPRETATION ------------------
    render_section_text(1, "METADATA INTERPRETATION", "Overview of the system's tables, data volumes, key structures, and relationships.")
    
    doc.add_paragraph("Table Summary & Sizing Assessment Table:").runs[0].bold = True
    table1 = doc.add_table(rows=1, cols=4)
    table1.style = 'Table Grid'
    hdr_cells = table1.rows[0].cells
    hdr_cells[0].text = 'Table Name'
    hdr_cells[1].text = 'Row Count'
    hdr_cells[2].text = 'Size (MB)'
    hdr_cells[3].text = 'Size Category'
    for c in hdr_cells:
        c.paragraphs[0].runs[0].font.bold = True
        set_cell_margins(c)
        
    for _, row in stats_df.iterrows():
        row_cells = table1.add_row().cells
        row_cells[0].text = str(row["table_name"])
        row_cells[1].text = str(row["row_count"])
        row_cells[2].text = str(row["size_mb"])
        row_cells[3].text = get_size_category(row["size_mb"], row["row_count"])
        for c in row_cells:
            set_cell_margins(c)
            
    doc.add_paragraph().paragraph_format.space_before = Pt(8)
    
    doc.add_paragraph("Key Identification Table:").runs[0].bold = True
    table2 = doc.add_table(rows=1, cols=3)
    table2.style = 'Table Grid'
    hdr_cells = table2.rows[0].cells
    hdr_cells[0].text = 'Table Name'
    hdr_cells[1].text = 'Column Name'
    hdr_cells[2].text = 'Key Type'
    for c in hdr_cells:
        c.paragraphs[0].runs[0].font.bold = True
        set_cell_margins(c)
        
    for _, row in columns_df.iterrows():
        t_name = row["TableName"]
        c_name = row["ColumnName"]
        c_lower = c_name.lower()
        is_pk = "id" in c_lower or "key" in c_lower
        is_fk = False
        if not dep_df.empty:
            is_fk = c_name in dep_df["parent_table"].values or any(
                (dep_df["parent_table"] == t_name) & (dep_df["fk_name"].str.contains(c_name, case=False, na=False))
            )
            
        if is_pk or is_fk:
            row_cells = table2.add_row().cells
            row_cells[0].text = str(t_name)
            row_cells[1].text = str(c_name)
            row_cells[2].text = "Primary Key Candidate" if is_pk else "Foreign Key Candidate"
            for c in row_cells:
                set_cell_margins(c)
                
    doc.add_paragraph().paragraph_format.space_before = Pt(8)

    # ------------------ SECTION 2: DEPENDENCY ANALYSIS ------------------
    render_section_text(2, "DEPENDENCY ANALYSIS", "Relational dependency mapping and topological sequence analysis.")

    # ------------------ SECTION 3: MIGRATION SEQUENCE ------------------
    render_section_text(3, "MIGRATION SEQUENCE", "Topological layer execution sequence for parallel migration.")

    # ------------------ SECTION 4: BATCH MIGRATION PLAN ------------------
    render_section_text(4, "BATCH MIGRATION PLAN", "Categorization of objects into parallelized execution batches.")

    # ------------------ SECTION 5: MEDALLION ARCHITECTURE MAPPING ------------------
    render_section_text(5, "MEDALLION ARCHITECTURE MAPPING", "Architectural categorization into Bronze, Silver, and Gold lakehouse layers.")

    # ------------------ SECTION 6: MICROSOFT FABRIC ARCHITECTURE ------------------
    render_section_text(6, "MICROSOFT FABRIC ARCHITECTURE", "Target cloud platform architecture layout in Microsoft Fabric.")

    # ------------------ SECTION 7: FINAL ARCHITECTURE FLOW ------------------
    render_section_text(7, "FINAL ARCHITECTURE FLOW", "End-to-end data flow mapping from source ingestion to lakehouse layers and reports.")

    # ------------------ SECTION 8: EXECUTION PLAN ------------------
    render_section_text(8, "EXECUTION PLAN", "Table-wise load strategies and parallelization execution guidelines.")

    # ------------------ SECTION 9: TOKEN AND COST REPORT ------------------
    p_h9 = doc.add_paragraph()
    r = p_h9.add_run("SECTION 9: TOKEN AND COST REPORT")
    r.font.size = Pt(18)
    r.font.bold = True
    r.font.color.rgb = RGBColor(15, 76, 129)
    p_h9.paragraph_format.space_before = Pt(18)
    
    sec9_raw = sections.get(9, "").strip()
    if sec9_raw:
        for line in sec9_raw.split("\n"):
            line_str = line.strip().replace("###", "").replace("**", "").replace("__", "").replace("|", "")
            if line_str:
                p = doc.add_paragraph()
                p.paragraph_format.space_after = Pt(4)
                p.add_run(line_str)
    elif tokens_used:
        prompt_cost = (tokens_used["prompt"] / 1000000.0) * 0.15
        comp_cost = (tokens_used["completion"] / 1000000.0) * 0.60
        total_cost = prompt_cost + comp_cost
        
        doc.add_paragraph(f"- Prompt Tokens: {tokens_used['prompt']}").paragraph_format.left_indent = Inches(0.25)
        doc.add_paragraph(f"- Completion Tokens: {tokens_used['completion']}").paragraph_format.left_indent = Inches(0.25)
        doc.add_paragraph(f"- Total Tokens: {tokens_used['total']}").paragraph_format.left_indent = Inches(0.25)
        doc.add_paragraph(f"- Estimated Cost: ${total_cost:.5f} USD").paragraph_format.left_indent = Inches(0.25)
    else:
        doc.add_paragraph("- Prompt Tokens: N/A").paragraph_format.left_indent = Inches(0.25)
        doc.add_paragraph("- Completion Tokens: N/A").paragraph_format.left_indent = Inches(0.25)
        doc.add_paragraph("- Total Tokens: N/A").paragraph_format.left_indent = Inches(0.25)
        doc.add_paragraph("- Estimated Cost: N/A").paragraph_format.left_indent = Inches(0.25)
        
    doc.save(output_path)
    print(f"[INFO] Successfully saved Migration Plan Report.")
